namespace ActivationPlanner.ProcessEngine.Nec;

/// <summary>
/// One wire segment group (a NEC <c>GW</c> card): a straight conductor from
/// (<paramref name="X1"/>,<paramref name="Y1"/>,<paramref name="Z1"/>) to
/// (<paramref name="X2"/>,<paramref name="Y2"/>,<paramref name="Z2"/>) split into
/// <paramref name="Segments"/> segments. All lengths are metres.
/// </summary>
public sealed record NecWire(
    int Tag,
    int Segments,
    double X1, double Y1, double Z1,
    double X2, double Y2, double Z2,
    double RadiusMetres);

/// <summary>
/// Ground model for a NEC <c>GN</c> card. Absence of a ground means a free-space model.
/// </summary>
/// <param name="Type">GN ground type (2 = finite/Sommerfeld with dielectric &amp; conductivity, 1 = perfect).</param>
/// <param name="DielectricConstant">Relative permittivity of the ground.</param>
/// <param name="ConductivitySm">Ground conductivity in S/m.</param>
public sealed record NecGround(int Type, double DielectricConstant, double ConductivitySm);

/// <summary>Feed point for a NEC <c>EX</c> voltage-source card.</summary>
/// <param name="Tag">Wire tag to feed.</param>
/// <param name="Segment">Segment number within that wire (1-based).</param>
/// <param name="VoltageReal">Real part of the applied voltage (typically 1.0).</param>
/// <param name="VoltageImag">Imaginary part of the applied voltage (typically 0.0).</param>
public sealed record NecExcitation(int Tag, int Segment, double VoltageReal = 1.0, double VoltageImag = 0.0);

/// <summary>
/// A NEC <c>RP</c> radiation-pattern request. The defaults sweep an elevation cut (theta from
/// zenith to horizon in 5° steps at a fixed azimuth), which is what the planner needs to read a
/// take-off angle and peak gain.
/// </summary>
public sealed record NecRadiationPattern(
    int ThetaCount = 19,
    int PhiCount = 1,
    double ThetaStartDeg = 0,
    double PhiStartDeg = 0,
    double ThetaStepDeg = 5,
    double PhiStepDeg = 0);

/// <summary>
/// A complete NEC2 geometry deck as primitive parameters: the wires, the frequency, an optional
/// ground, the feed, and the radiation-pattern request. This is a Layer-1 wire-format DTO — no
/// antenna physics, no planner domain (those live in PropagationModel, which builds this).
/// </summary>
public sealed record NecGeometryInput
{
    /// <summary>Free-text comment lines (emitted as CM cards).</summary>
    public IReadOnlyList<string> Comments { get; init; } = ["Generated by Activation Planner"];

    /// <summary>The wire structure. At least one wire is required.</summary>
    public required IReadOnlyList<NecWire> Wires { get; init; }

    /// <summary>Analysis frequency in MHz.</summary>
    public required double FrequencyMhz { get; init; }

    /// <summary>Ground model, or null for a free-space model.</summary>
    public NecGround? Ground { get; init; }

    /// <summary>Feed point.</summary>
    public required NecExcitation Excitation { get; init; }

    /// <summary>Radiation-pattern request.</summary>
    public NecRadiationPattern RadiationPattern { get; init; } = new();
}
