using System.Globalization;
using static ActivationPlanner.ProcessEngine.Voacap.VoacapCardFormat;

namespace ActivationPlanner.ProcessEngine.Voacap;

/// <summary>
/// Renders a <see cref="VoacapDeckInput"/> into a VOACAP point-to-point (METHOD 30)
/// input deck — the fixed-column text file the VOACAP engine reads.
/// <para>
/// Pure and deterministic: no I/O, no clock, no domain knowledge. Column positions
/// come entirely from <see cref="VoacapCardFormat"/> and are verified byte-for-byte
/// against a real known-good deck (<c>tests/p2p/test01.dat</c>) in the ProcessEngine
/// tests. Fixed-column formatting is the most error-prone part of the VOACAP
/// shell-out, so the layout is expressed in explicit 1-based columns rather than by
/// counting spaces.
/// </para>
/// </summary>
public sealed class VoacapDeckWriter
{
    /// <summary>Render the deck as a single string using <see cref="VoacapCardFormat.LineSeparator"/>.</summary>
    public string Write(VoacapDeckInput input)
    {
        ArgumentNullException.ThrowIfNull(input);
        Validate(input);

        var lines = new List<string>
        {
            Comment("Generated by Activation Planner"),
            LineMax(input.LinesPerPage),
            Coeffs(input.Coefficients),
            Time(input.StartHourUtc, input.StopHourUtc, input.HourIncrement),
            Month(input.Year, input.MonthValue),
            Sunspot(input.SunspotNumber),
            Label(input.TxLabel, input.RxLabel),
            Circuit(input),
            System(input),
            Fprob(input.LayerProbabilities),
            Antenna(1, input.TxAntenna),
            Antenna(2, input.RxAntenna),
            Frequency(input.FrequenciesMhz),
            Method(input.Method),
            new FixedColumnLine().Append("EXECUTE").ToString(),
            new FixedColumnLine().Append("QUIT").ToString(),
        };

        // VOACAP reads by fixed column, so trailing spaces beyond a card's last field are
        // never significant; trim them so output matches VOACAP's own decks byte-for-byte.
        return string.Join(LineSeparator, lines.Select(l => l.TrimEnd())) + LineSeparator;
    }

    private static void Validate(VoacapDeckInput input)
    {
        if (input.FrequenciesMhz.Count == 0)
            throw new ArgumentException("At least one frequency is required.", nameof(input));
        if (input.FrequenciesMhz.Count > MaxFrequencies)
            throw new ArgumentException(
                $"A FREQUENCY card holds at most {MaxFrequencies} frequencies; got {input.FrequenciesMhz.Count}.",
                nameof(input));
        if (input.LayerProbabilities.Count != 4)
            throw new ArgumentException("FPROB requires exactly four layer-probability values.", nameof(input));
        if (input.TxAntenna.AntennaFile.Length > AntennaFileWidth)
            throw new ArgumentException(
                $"TX antenna file exceeds {AntennaFileWidth} columns.", nameof(input));
        if (input.RxAntenna.AntennaFile.Length > AntennaFileWidth)
            throw new ArgumentException(
                $"RX antenna file exceeds {AntennaFileWidth} columns.", nameof(input));
    }

    // ---- individual cards (each returns one rendered line) ----

    private static string Comment(string text) =>
        new FixedColumnLine().Append(Keyword("COMMENT")).Place(11, text).ToString();

    private static string LineMax(int lines) =>
        new FixedColumnLine().Append(Keyword("LINEMAX")).Place(11, IntField(lines))
            .Place(23, "number of lines-per-page").ToString();

    private static string Coeffs(VoacapCoefficients c) =>
        new FixedColumnLine().Append(Keyword("COEFFS"))
            .Place(11, c == VoacapCoefficients.Ursi88 ? "URSI88" : "CCIR").ToString();

    private static string Time(int start, int stop, int inc) =>
        new FixedColumnLine().Append(Keyword("TIME"))
            .Place(11, IntField(start))
            .Place(16, IntField(stop))
            .Place(21, IntField(inc))
            .Place(26, IntField(1)) // time code 1 = UTC
            .ToString();

    private static string Month(int year, double monthValue) =>
        // Year is right-justified in a 5-column field (cols 11-15); the month F5.2 follows at col 16.
        new FixedColumnLine().Append(Keyword("MONTH"))
            .Place(11, IntField(year, NumericFieldWidth))
            .Place(16, RealFieldFixed(monthValue, NumericFieldWidth, 2))
            .ToString();

    private static string Sunspot(double ssn) =>
        // VOACAP writes the SSN with a trailing decimal point (e.g. "100."), right-justified.
        new FixedColumnLine().Append(Keyword("SUNSPOT"))
            .Place(11, SunspotField(ssn)).ToString();

    private static string SunspotField(double ssn)
    {
        string text = ssn == Math.Floor(ssn)
            ? ((long)ssn).ToString(CultureInfo.InvariantCulture) + "."
            : ssn.ToString("0.0", CultureInfo.InvariantCulture);
        return text.PadLeft(NumericFieldWidth);
    }

    private static string Label(string tx, string rx) =>
        new FixedColumnLine().Append(Keyword("LABEL"))
            .Place(11, Fit(tx, 20))
            .Place(31, Fit(rx, 20))
            .ToString();

    private static string Circuit(VoacapDeckInput i)
    {
        var line = new FixedColumnLine().Append(Keyword("CIRCUIT"));
        PlaceCoordinate(line, 11, i.TxLatitudeDeg, isLatitude: true);
        PlaceCoordinate(line, 21, i.TxLongitudeDeg, isLatitude: false);
        PlaceCoordinate(line, 31, i.RxLatitudeDeg, isLatitude: true);
        PlaceCoordinate(line, 41, i.RxLongitudeDeg, isLatitude: false);
        line.Place(49, i.Path == VoacapPath.Long ? "L" : "S");
        line.Place(50, IntField(0, 6));
        return line.ToString();
    }

    /// <summary>
    /// Place a coordinate as VOACAP magnitude + hemisphere: value right-justified in the
    /// 5-column field starting at <paramref name="valueColumn"/>, hemisphere letter in the
    /// column immediately after. Two decimals for magnitudes under 100°, one decimal at or
    /// above (longitudes up to 180° must still fit five columns).
    /// </summary>
    private static void PlaceCoordinate(FixedColumnLine line, int valueColumn, double signedDeg, bool isLatitude)
    {
        double magnitude = Math.Abs(signedDeg);
        int decimals = magnitude < 100.0 ? 2 : 1;
        char hemisphere = isLatitude
            ? (signedDeg < 0 ? 'S' : 'N')
            : (signedDeg < 0 ? 'W' : 'E');
        line.Place(valueColumn, RealFieldFixed(magnitude, NumericFieldWidth, decimals));
        line.Place(valueColumn + NumericFieldWidth, hemisphere.ToString());
    }

    private static string System(VoacapDeckInput i)
    {
        // SYSTEM field order (voacapl read_asc.for): reserved(1.0), noise, min-angle,
        // required-reliability, required-SNR, multipath-power-tol, multipath-delay-tol.
        var line = new FixedColumnLine().Append(Keyword("SYSTEM"));
        double[] fields =
        [
            1.0,
            i.NoiseDbw,
            i.MinTakeoffAngleDeg,
            i.RequiredReliabilityPercent,
            i.RequiredSnrDb,
            i.MultipathPowerToleranceDb,
            i.MultipathDelayToleranceMs,
        ];
        for (int f = 0; f < fields.Length; f++)
            line.Place(11 + f * NumericFieldWidth, RealField(fields[f]));
        return line.ToString();
    }

    private static string Fprob(IReadOnlyList<double> p)
    {
        var line = new FixedColumnLine().Append(Keyword("FPROB"));
        for (int f = 0; f < p.Count; f++)
            line.Place(11 + f * NumericFieldWidth, RealFieldFixed(p[f], NumericFieldWidth, 2));
        return line.ToString();
    }

    private static string Antenna(int number, VoacapAntenna a) =>
        new FixedColumnLine().Append(Keyword("ANTENNA"))
            .Place(11, IntField(number))
            .Place(16, IntField(number))
            .Place(21, IntField(a.MinFrequencyMhz))
            .Place(26, IntField(a.MaxFrequencyMhz))
            .Place(31, RealFieldFixed(a.GainOffsetDbi, 10, 3))
            .Place(41, "[")
            .Place(42, a.AntennaFile.PadRight(AntennaFileWidth))
            .Place(63, "]")
            .Place(64, RealFieldFixed(a.BearingDeg, NumericFieldWidth, 1))
            .Place(69, RealFieldFixed(a.PowerKw, 10, 4))
            .ToString();

    private static string Frequency(IReadOnlyList<double> freqs)
    {
        var line = new FixedColumnLine().Append(Keyword("FREQUENCY"));
        for (int f = 0; f < MaxFrequencies; f++)
        {
            double v = f < freqs.Count ? freqs[f] : 0.0;
            line.Place(11 + f * NumericFieldWidth, RealFieldFixed(v, NumericFieldWidth, 2));
        }
        return line.ToString();
    }

    private static string Method(int method) =>
        new FixedColumnLine().Append(Keyword("METHOD"))
            .Place(11, IntField(method))
            .Place(16, IntField(0))
            .ToString();

    /// <summary>Left-justify text into a fixed width, truncating if longer.</summary>
    private static string Fit(string text, int width)
    {
        text ??= string.Empty;
        return text.Length > width ? text[..width] : text.PadRight(width);
    }
}
